// Mock data for company dashboard

export const mockJobs = [
  {
    id: "1",
    title: "Senior Data Annotator - Computer Vision",
    status: "open",
    applicants: 24,
    created: "2025-01-15",
    employmentType: "Full-time",
    payRange: "$65,000 - $85,000",
    location: "Remote",
    description: "We're seeking an experienced data annotator specializing in computer vision projects...",
    tags: ["Computer Vision", "Remote", "Full-time"],
  },
  {
    id: "2",
    title: "NLP Data Labeling Specialist",
    status: "open",
    applicants: 18,
    created: "2025-01-20",
    employmentType: "Contract",
    payRange: "$50/hr",
    location: "Remote",
    description: "Join our team to label and categorize text data for natural language processing models...",
    tags: ["NLP", "Contract", "Remote"],
  },
  {
    id: "3",
    title: "Audio Transcription Annotator",
    status: "closed",
    applicants: 42,
    created: "2024-12-10",
    employmentType: "Part-time",
    payRange: "$35,000 - $45,000",
    location: "Hybrid - San Francisco",
    description: "Part-time role focused on audio transcription and annotation for speech recognition systems...",
    tags: ["Audio", "Part-time", "Hybrid"],
  },
];

export const mockApplicants = [
  {
    id: "1",
    name: "Sarah Chen",
    email: "sarah.chen@email.com",
    jobId: "1",
    jobTitle: "Senior Data Annotator - Computer Vision",
    stage: "interview",
    appliedDate: "2025-01-16",
    score: 92,
    avatar: "SC",
    resumeUrl: "#",
    coverNote: "I have 4 years of experience in computer vision annotation, working with autonomous vehicle datasets...",
  },
  {
    id: "2",
    name: "Marcus Rodriguez",
    email: "marcus.r@email.com",
    jobId: "1",
    jobTitle: "Senior Data Annotator - Computer Vision",
    stage: "screen",
    appliedDate: "2025-01-18",
    score: 88,
    avatar: "MR",
    resumeUrl: "#",
    coverNote: "Passionate about AI and data quality. My background in image processing makes me a great fit...",
  },
  {
    id: "3",
    name: "Emily Watson",
    email: "emily.watson@email.com",
    jobId: "2",
    jobTitle: "NLP Data Labeling Specialist",
    stage: "applied",
    appliedDate: "2025-01-22",
    score: null,
    avatar: "EW",
    resumeUrl: "#",
    coverNote: "I'm excited to bring my linguistics background to your NLP annotation projects...",
  },
  {
    id: "4",
    name: "David Kim",
    email: "david.kim@email.com",
    jobId: "1",
    jobTitle: "Senior Data Annotator - Computer Vision",
    stage: "offer",
    appliedDate: "2025-01-14",
    score: 95,
    avatar: "DK",
    resumeUrl: "#",
    coverNote: "With extensive experience in bounding box annotation and semantic segmentation...",
  },
  {
    id: "5",
    name: "Jessica Park",
    email: "jessica.p@email.com",
    jobId: "2",
    jobTitle: "NLP Data Labeling Specialist",
    stage: "hired",
    appliedDate: "2025-01-12",
    score: 94,
    avatar: "JP",
    resumeUrl: "#",
    coverNote: "Thrilled to join the team and contribute to cutting-edge NLP projects...",
  },
];

export const mockThreads = [
  {
    id: "1",
    participantName: "Sarah Chen",
    participantAvatar: "SC",
    context: "Senior Data Annotator - Computer Vision",
    contextType: "job",
    lastMessage: "Thank you for the update! I'm available for the interview next Tuesday.",
    timestamp: "2025-01-24T14:30:00",
    unread: true,
    applicantId: "1",
    jobId: "1",
  },
  {
    id: "2",
    participantName: "David Kim",
    participantAvatar: "DK",
    context: "Senior Data Annotator - Computer Vision",
    contextType: "job",
    lastMessage: "I'd love to discuss the offer details. When would be a good time?",
    timestamp: "2025-01-24T10:15:00",
    unread: true,
    applicantId: "4",
    jobId: "1",
  },
  {
    id: "3",
    participantName: "Marcus Rodriguez",
    participantAvatar: "MR",
    context: "Computer Vision Basics",
    contextType: "module",
    lastMessage: "I completed the module. Could you review my submission?",
    timestamp: "2025-01-23T16:45:00",
    unread: false,
    moduleId: "1",
  },
];

export const mockModules = [
  {
    id: "1",
    title: "Computer Vision Basics",
    type: "image",
    description: "Fundamental concepts in image annotation including bounding boxes and segmentation",
    difficulty: "beginner",
    attempts: 156,
    avgScore: 84,
    status: "active",
    participants: 89,
  },
  {
    id: "2",
    title: "Advanced NLP Labeling",
    type: "text",
    description: "Named entity recognition, sentiment analysis, and text classification",
    difficulty: "advanced",
    attempts: 94,
    avgScore: 76,
    status: "active",
    participants: 52,
  },
  {
    id: "3",
    title: "Audio Transcription Practice",
    type: "audio",
    description: "Practice transcribing various audio samples with different accents and quality",
    difficulty: "intermediate",
    attempts: 203,
    avgScore: 91,
    status: "active",
    participants: 127,
  },
  {
    id: "4",
    title: "Video Annotation Fundamentals",
    type: "video",
    description: "Frame-by-frame annotation and object tracking in video sequences",
    difficulty: "intermediate",
    attempts: 67,
    avgScore: 79,
    status: "draft",
    participants: 34,
  },
];

export const mockTeam = [
  {
    id: "1",
    name: "Jane Doe",
    email: "jane.doe@company.com",
    avatar: "JD",
    role: "owner",
  },
  {
    id: "2",
    name: "John Smith",
    email: "john.smith@company.com",
    avatar: "JS",
    role: "manager",
  },
  {
    id: "3",
    name: "Alice Johnson",
    email: "alice.j@company.com",
    avatar: "AJ",
    role: "recruiter",
  },
];

export const mockInvoices = [
  {
    id: "inv_001",
    date: "2025-01-01",
    amount: "$299.00",
    status: "paid",
  },
  {
    id: "inv_002",
    date: "2024-12-01",
    amount: "$299.00",
    status: "paid",
  },
  {
    id: "inv_003",
    date: "2024-11-01",
    amount: "$299.00",
    status: "paid",
  },
];
